{{- if .Values.global.semagrow.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "semagrow.fullname" . }}-svc
  namespace: {{ $.Release.Namespace }}
  labels:
    app: semagrow
spec:
  type: {{ .Values.serviceType }}
  {{- if eq .Values.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.minioLoadBalancerIP }}
  {{- end }}
  selector:
    app: {{ template "semagrow.name" . }}
    release: {{ .Release.Name }}
    component: app
  ports:
  - name: http
    port: 8080
    targetPort: {{ .Values.servicePort }}
    protocol: TCP
{{- end }}
